# These are supported funding model platforms

# github: [AgenciaFER]
# patreon: aws-multi-account-agent
# open_collective: aws-multi-account-agent
# ko_fi: awsagent
# tidelift: pypi/aws-multi-account-agent
# community_bridge: aws-multi-account-agent
# liberapay: aws-agent
# issuehunt: AgenciaFER
# otechie: aws-multi-account-agent
# custom: ['https://aws-multi-account-agent.com/donate']

# Note: Uncomment and configure the funding options you want to use
