# Configuração padrão do AWS Agent
# Este arquivo contém as configurações padrão da aplicação

# Configurações da aplicação
app:
  name: "AWS Multi-Account Agent"
  version: "1.0.0"
  description: "Agente para gerenciamento de múltiplas contas AWS"

# Configurações de log
logging:
  level: "INFO"
  file: "aws-agent.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5

# Configurações AWS
aws:
  default_region: "us-east-1"
  session_timeout: 3600  # 1 hora
  max_retries: 3
  retry_delay: 1.0

# Configurações de segurança
security:
  encryption_algorithm: "AES-256"
  key_derivation: "PBKDF2"
  salt_length: 32
  iterations: 100000

# Configurações de interface
interface:
  cli:
    pager: true
    colors: true
    table_format: "grid"
    max_width: 120
  
  output:
    timestamp: true
    verbose: false
    json: false

# Configurações de backup
backup:
  auto_backup: true
  backup_interval: "daily"
  max_backups: 30
  compression: true

# Configurações de cache
cache:
  enabled: true
  ttl: 300  # 5 minutos
  max_size: 100

# Configurações de monitoramento
monitoring:
  enabled: true
  metrics_collection: true
  performance_logging: false
