security:
  audit:
    enabled: true
    encrypt_logs: true
    log_level: INFO
    retention_days: 365
    sanitize_logs: true
  encryption:
    algorithm: AES-256-GCM
    iterations: 150000
    key_derivation: PBKDF2
    salt_length: 32
  monitoring:
    failed_login_threshold: 3
    metrics_collection: true
    real_time_alerts: true
    suspicious_activity_detection: true
  network:
    force_tls: true
    min_tls_version: '1.3'
    timeout: 30
    verify_certificates: true
  session:
    auto_refresh: true
    lockout_time: 1800
    max_retries: 2
    refresh_threshold: 300
    timeout: 1800
  validation:
    check_resource_existence: true
    require_mfa: false
    strict_mode: true
    validate_permissions: true
